### ISSUE TITLE
kotlin version necessary

### ISSUE THREAD

**Issue by baudelioandalon** [Devlight/CornerCutLinearLayout#3]
Hi, i'm adding your library, i think is very interesting, but is incompatibility yet, or 
i'dont have what is the library necesssary to compile in my android project
this is the error

Could not find org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4-M1

**Comment by XtreeIvI** [comment]
All you need is to properly configure kotlin for your project. 
See respective official kotlin setup for android.
Also make sure you include plugins in your target build gradle:
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions' (optional)

Also there is known issue that latest canary android studio throw warning to this kotlin version.

**Comment by XtreeIvI** [comment]
configure kotlin version and plugin properly

>
